name: "Send Email after workflow"

on:
    workflow_dispatch:

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Steup python env"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: "Install Dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install smtplib email

            - name: "Send mail by exectuing python script"
              run: python script.py
              env: 
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id}}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECEVIER_EMAIL: ${{ secrets.RECEVIER_EMAIL }}